from ..errors import Error


class UserNotFoundError(Error):
    pass
